### ISSUE TITLE
Courses crashing on evaluation screen

### ISSUE THREAD

**Issue by Connormgs** [Connormgs/Simply-ITG#9]
Reported by a user, need to test to get more information.

**Comment by arceuss** [comment]
![unknown-400](https://user-images.githubusercontent.com/28229451/118019296-0e917c00-b316-11eb-94eb-90ba50018ff2.png)
crash happens for me on notitg after doing a course

**Comment by Connormgs** [comment]
Issue has been fixed, waiting for confirmation from users before closing issue.

**Comment by arceuss** [comment]
seems to work fine for me on nitg

**Comment by Connormgs** [comment]
Great to hear! I'll go ahead and close this issue.
